---
dist-rtr01:
    hostname: 10.10.20.175
    port: 22
    platform: cisco_xe
    groups:
        - cisco
    data:
        role: dist
        type: network_device

dist-rtr02:
    hostname: 10.10.20.176
    port: 22
    platform: cisco_xe
    groups:
        - cisco
    data:
        role: dist
        type: network_device

dist-sw01:
    hostname: 10.10.20.177
    port: 22
    platform: cisco_nxos
    groups:
        - cisco
    data:
        role: dist
        type: network_device

dist-sw02:
    hostname: 10.10.20.178
    port: 22
    platform: cisco_nxos
    groups:
        - cisco
    data:
        role: dist
        type: network_device